version: '3.8'

services:
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - msa-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - eureka
    networks:
      - msa-net

  test-service:
    build: ./test-service
    container_name: test-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - kafka
    networks:
      - msa-net

  consumer-service:
    build: ./consumer-service
    container_name: consumer
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - eureka
    networks:
      - msa-net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - msa-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_PROCESS_ROLES: broker
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_KRAFT_MODE_ENABLED: no
      KAFKA_CFG_BROKER_ID: 1
    depends_on:
      - zookeeper
    networks:
      - msa-net

networks:
  msa-net:
