spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: test-service-route
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test-service/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    enable:
      system.processor: false

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP}
  refresh:
    expiration: ${REFRESH_EXP}

exclude-auth-path-patterns:
  paths:
    - path-pattern: /health-check
      method: GET