spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: welfare-service-route
          uri: lb://WELFARE-SERVICE
          predicates:
            - Path=/api/welfare/**
        - id: board-service-route
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/board/**
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka

management:
  metrics:
    enable:
      system.processor: false

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600

jwt:
  key: ${JWT_KEY}

exclude-auth-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST