spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
server:
  port: 8081

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP}
  refresh:
    expiration: ${REFRESH_EXP}

exclude-auth-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST
    - path-pattern: /api/users/validate
      method: GET

management:
  metrics:
    enable:
      system.processor: false
