name: Run Tests and Upload to Tricentis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle tests
        run: ./gradlew test

      - name: Upload test results to Tricentis
        uses: tricentis/testmanagement-for-jira-action@v1
        with:
          server: https://software-engineering-team-17.atlassian.net
          project: SE
          testExecutionKey: SE-TR-1        # Tricentis에서 생성한 실행 ID
          testResultFile: build/test-results/test/TEST-*.xml
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
