spring:
  application:
    name: welfare-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
server:
  port: 8083

management:
  metrics:
    enable:
      system.processor: false
