spring:
  application:
    name: welfare-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: admin

jwt:
  key: ${JWT_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
server:
  port: 8083

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
